name: Sync Pull Request to Azure Boards

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches:
      - master

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:
         ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
         github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
         ado_organization: "msazure"
         ado_project: "One"
         ado_area_path: "${{ secrets.AREA }}"
         ado_iteration_path: "${{ secrets.ITERATION_PATH }}"
         ado_wit: "Bug"
         ado_new_state: "New"
         ado_active_state: "Active"
         ado_close_state: "Closed"
         ado_bypassrules: false
         log_level: 100
